import { 
  Plane, Bus, Train, Car, Navigation, Hotel, Map, Utensils, Box, MapPin, 
  Camera, Coffee, Music, Heart, Star, ShoppingBag, Landmark,
  Umbrella, Palmtree, Mountain, Waves, Sun, Cloud, Moon,
  Ticket, Briefcase, Glasses, Wallet, CreditCard, Gift, Beer, Cake,
  Wine, Pizza, Sandwich, Soup, IceCream, Apple,
  BusFront, CarFront, Bike, Ship, TramFront, CableCar,
  Home, Building, Castle, School, Church,
  Flag, Anchor, Compass, Globe, Luggage, MapPinned,
  Wifi, Phone, Battery, Bluetooth, Laptop, Tablet, Smartphone,
  Activity, HeartPulse, Stethoscope, Microscope, Pill,
  Tent, Footprints, Trees, Flower, Leaf,
  Wind, Thermometer, Droplets, Snowflake, Sparkles,
  Award, Medal, Trophy, Target, Dumbbell,
  MessageSquare, Mail, Bell, Settings, User, Users,
  CheckCircle2, AlertCircle, HelpCircle, Info,
  Plus, Minus, ArrowRight, ArrowLeft, ChevronRight, ChevronLeft,
  RotateCcw, RefreshCcw, LayoutGrid, List, Grid,
  Maximize2, Minimize2, ExternalLink, Share2, Download, Upload,
  Paperclip, Scissors, Pencil, Eraser, Trash2, Save,
  Eye, EyeOff, Lock, Unlock, Key, Shield, ShieldCheck,
  Zap, Flame, Droplet, Ghost, Skull, CloudRain, CloudLightning,
  Construction, HardHat, Hammer, Wrench, Ruler,
  Mic, Radio, Tv, Headphones, Speaker,
  Gamepad, Joystick, Mouse, Keyboard,
  Monitor, Printer, Database,
  Server, Cpu,
  Lightbulb, Book, GraduationCap,
  Clock, Timer, Hourglass, History,
  DollarSign, Euro, PoundSterling, Bitcoin,
  Tag, Tags, Receipt, Calculator,
  Filter, SortAsc, SortDesc, SearchCheck,
  CameraOff, Video, Film, Image, Images,
  Layout, Kanban, Table, BarChart, PieChart, LineChart,
  Code, Terminal, FileCode, FileText, FileJson,
  Hash, Languages, Quote, Type,
  Cloudy, SunMedium, SunDim, Rainbow,
  Tornado, CloudSun, CloudMoon,
  ParkingCircle, Accessibility, Baby,
  Citrus, Cherry, Grape, 
  Popcorn, CookingPot, ChefHat,
  Gem, ShoppingCart, 
  PartyPopper,
  AlarmClock, BellRing, Inbox, Send,
  Pin, Bookmark, StickyNote,
  Dna, Fingerprint, ScanFace, ScanBarcode,
  Chrome, Github, Twitter, Instagram, Linkedin, Youtube,
  Facebook, Twitch, Slack, Figma, Trello,
  Smile, Frown, Laugh, Angry,
  Wand2, ScissorsLineDashed, Lasso, Pipette,
  Layers, Combine, Group, Ungroup,
  Contrast, Palette, Brush, 
  Sticker, Shapes, Grid3X3,
  AlignLeft, AlignCenter, AlignRight, AlignJustify,
  Bold, Italic, Underline, Strikethrough,
  Highlighter, PencilLine, PenTool,
  Library, Trash, File, Folders,
  MailCheck, MailQuestion, MailPlus, MailMinus,
  MessageCircle, MessagesSquare, PhoneCall, PhoneForwarded,
  MonitorCheck, MonitorOff, MonitorSmartphone,
  ServerOff, DatabaseBackup, RadioTower,
  MemoryStick, HardDrive,
  Usb, MousePointer, HandMetal, HelpingHand,
  Clapperboard, Presentation, Podcast, Cast,
  LayoutTemplate, LayoutList, LayoutPanelLeft, LayoutPanelTop,
  TableProperties, Columns, Rows,
  Component, Puzzle, Boxes,
  Circle, Square, Triangle, Hexagon, Octagon, Pentagon,
  Diamond, Clock1, Clock2, Clock3, Clock4, Clock12,
  CalendarDays, CalendarPlus, CalendarMinus, CalendarRange,
  AlarmClockOff, TimerOff, TimerReset, StopCircle,
  Play, Pause, FastForward, Rewind, StepForward, StepBack,
  Volume2, VolumeX, Mic2, MicOff,
  BluetoothOff, WifiOff, NavigationOff,
  PlaneLanding, PlaneTakeoff, ShipWheel, Truck,
  ParkingMeter, Fuel, BatteryCharging,
  ZapOff, ThermometerSnowflake, ThermometerSun,
  Dribbble, Codepen, GitPullRequest, GitMerge, GitBranch,
  Github as GithubIcon, GitCommit, GitGraph,
  Backpack, Flashlight, Telescope, Compass as CompassIcon,
  Milestone, Route, RouteOff, Navigation2, MapPinOff,
  MountainSnow, Trees as TreesIcon, TreePine,
  Sunset, Sunrise, SunMedium as SunIcon,
  Dumbbell as DumbbellIcon, Trophy as TrophyIcon, Medal as MedalIcon,
  Goal as GoalIcon, HeartPulse as HeartIcon, Activity as ActivityIcon,
  Waves as WavesIcon, Anchor as AnchorIcon, Ship as ShipIcon,
  LifeBuoy, Martini as Cocktail, GlassWater,
  FerrisWheel, PartyPopper as PartyIcon,
  BaggageClaim, Wallet as WalletIcon, Receipt as ReceiptIcon,
  Globe as GlobeIcon, Landmark as LandmarkIcon, Castle as CastleIcon,
  Church as ChurchIcon, Building2, Warehouse,
  Beef, Candy, Cookie, Donut, Egg, Fish, Salad,
  Brain, Syringe,
  CloudDrizzle, CloudFog, Haze,
  Crown,
  Archive, FolderOpen, Notebook,
  Magnet, Plug, Power, 
  Volume, Volume1
} from 'lucide-react';

export const ICON_LIST: Record<string, any> = {
  Plane, Bus, Train, Car, Navigation, Hotel, Map, Utensils, Box, MapPin,
  Camera, Coffee, Music, Heart, Star, ShoppingBag, Landmark,
  Umbrella, Palmtree, Mountain, Waves, Sun, Cloud, Moon,
  Ticket, Briefcase, Glasses, Wallet, CreditCard, Gift, Beer, Cake,
  Wine, Pizza, Sandwich, Soup, IceCream, Apple,
  BusFront, CarFront, Bike, Ship, TramFront, CableCar,
  Home, Building, Castle, School, Church,
  Flag, Anchor, Compass, Globe, Luggage, MapPinned,
  Wifi, Phone, Battery, Bluetooth, Laptop, Tablet, Smartphone,
  Activity, HeartPulse, Stethoscope, Microscope, Pill,
  Tent, Footprints, Trees, Flower, Leaf,
  Wind, Thermometer, Droplets, Snowflake, Sparkles,
  Award, Medal, Trophy, Target, Dumbbell,
  MessageSquare, Mail, Bell, Settings, User, Users,
  CheckCircle2, AlertCircle, HelpCircle, Info,
  Plus, Minus, ArrowRight, ArrowLeft, ChevronRight, ChevronLeft,
  RotateCcw, RefreshCcw, LayoutGrid, List, Grid,
  Maximize2, Minimize2, ExternalLink, Share2, Download, Upload,
  Paperclip, Scissors, Pencil, Eraser, Trash2, Save,
  Eye, EyeOff, Lock, Unlock, Key, Shield, ShieldCheck,
  Zap, Flame, Droplet, Ghost, Skull, CloudRain, CloudLightning,
  Construction, HardHat, Hammer, Wrench, Ruler,
  Mic, Radio, Tv, Headphones, Speaker,
  Gamepad, Joystick, Mouse, Keyboard,
  Monitor, Printer, Database,
  Server, Cpu,
  Lightbulb, Book, GraduationCap,
  Clock, Timer, Hourglass, History,
  DollarSign, Euro, PoundSterling, Bitcoin,
  Tag, Tags, Receipt, Calculator,
  Filter, SortAsc, SortDesc, SearchCheck,
  CameraOff, Video, Film, Image, Images,
  Layout, Kanban, Table, BarChart, PieChart, LineChart,
  Code, Terminal, FileCode, FileText, FileJson,
  Hash, Languages, Quote, Type,
  Cloudy, SunMedium, SunDim, Rainbow,
  Tornado, CloudSun, CloudMoon,
  ParkingCircle, Accessibility, Baby,
  Citrus, Cherry, Grape, 
  Popcorn, CookingPot, ChefHat,
  Gem, ShoppingCart, 
  PartyPopper,
  AlarmClock, BellRing, Inbox, Send,
  Pin, Bookmark, StickyNote,
  Dna, Fingerprint, ScanFace, ScanBarcode,
  Chrome, Github, Twitter, Instagram, Linkedin, Youtube,
  Facebook, Twitch, Slack, Figma, Trello,
  Smile, Frown, Laugh, Angry,
  Wand2, ScissorsLineDashed, Lasso, Pipette,
  Layers, Combine, Group, Ungroup,
  Contrast, Palette, Brush, 
  Sticker, Shapes, Grid3X3,
  AlignLeft, AlignCenter, AlignRight, AlignJustify,
  Bold, Italic, Underline, Strikethrough,
  Highlighter, PencilLine, PenTool,
  Library, Trash, File, Folders,
  MailCheck, MailQuestion, MailPlus, MailMinus,
  MessageCircle, MessagesSquare, PhoneCall, PhoneForwarded,
  MonitorCheck, MonitorOff, MonitorSmartphone,
  ServerOff, DatabaseBackup, RadioTower,
  MemoryStick, HardDrive,
  Usb, MousePointer, HandMetal, HelpingHand,
  Clapperboard, Presentation, Podcast, Cast,
  LayoutTemplate, LayoutList, LayoutPanelLeft, LayoutPanelTop,
  TableProperties, Columns, Rows,
  Component, Puzzle, Boxes,
  Circle, Square, Triangle, Hexagon, Octagon, Pentagon,
  Diamond, Clock1, Clock2, Clock3, Clock4, Clock12,
  CalendarDays, CalendarPlus, CalendarMinus, CalendarRange,
  AlarmClockOff, TimerOff, TimerReset, StopCircle,
  Play, Pause, FastForward, Rewind, StepForward, StepBack,
  Volume2, VolumeX, Mic2, MicOff,
  BluetoothOff, WifiOff, NavigationOff,
  PlaneLanding, PlaneTakeoff, ShipWheel, Truck,
  ParkingMeter, Fuel, BatteryCharging,
  ZapOff, ThermometerSnowflake, ThermometerSun,
  Dribbble, Codepen, GitPullRequest, GitMerge, GitBranch,
  GithubIcon, GitCommit, GitGraph,
  Backpack, Flashlight, Telescope, CompassIcon,
  Milestone, Route, RouteOff, Navigation2, MapPinOff,
  MountainSnow, TreesIcon, TreePine,
  Sunset, Sunrise, SunIcon,
  DumbbellIcon, TrophyIcon, MedalIcon,
  GoalIcon, HeartIcon, ActivityIcon,
  WavesIcon, AnchorIcon, ShipIcon,
  LifeBuoy, Cocktail, GlassWater,
  FerrisWheel, PartyIcon,
  BaggageClaim, WalletIcon, ReceiptIcon,
  GlobeIcon, LandmarkIcon, CastleIcon,
  ChurchIcon, Building2, Warehouse,
  Beef, Candy, Cookie, Donut, Egg, Fish, Salad,
  Brain, Syringe,
  CloudDrizzle, CloudFog, Haze,
  Crown,
  Archive, FolderOpen, Notebook,
  Magnet, Plug, Power, 
  Volume, Volume1
};
